CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(120) NOT NULL UNIQUE,
  nombre_visible VARCHAR(180) NOT NULL,
  fuero VARCHAR(120) NOT NULL,
  origen VARCHAR(20) NOT NULL DEFAULT 'AD',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE modulos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  orden INT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE permisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NOT NULL
);

CREATE TABLE usuario_roles (
  usuario_id BIGINT NOT NULL,
  rol_id BIGINT NOT NULL,
  PRIMARY KEY (usuario_id, rol_id)
);

CREATE TABLE rol_modulo_permisos (
  rol_id BIGINT NOT NULL,
  modulo_id BIGINT NOT NULL,
  permiso_id BIGINT NOT NULL,
  PRIMARY KEY (rol_id, modulo_id, permiso_id)
);

CREATE TABLE credenciales_locales (
  usuario_id BIGINT PRIMARY KEY,
  password_hash VARCHAR(255) NOT NULL,
  requiere_cambio_clave BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE equipos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  ultimo_usuario VARCHAR(120),
  fuero VARCHAR(120) NOT NULL,
  ip VARCHAR(45),
  sistema_operativo VARCHAR(180),
  procesador VARCHAR(255),
  ram_mb INT,
  ram_detalles VARCHAR(500),
  ram_seriales VARCHAR(500),
  discos_modelos VARCHAR(500),
  discos_seriales VARCHAR(500),
  motherboard_modelo VARCHAR(255),
  motherboard_serial VARCHAR(255),
  monitores VARCHAR(500),
  teclado VARCHAR(180),
  mouse VARCHAR(180),
  impresora VARCHAR(180),
  monitoreo VARCHAR(60) NOT NULL DEFAULT 'SIN_REPORTE',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  ultimo_reporte_en TIMESTAMP,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO usuarios (id, username, nombre_visible, fuero, origen, activo)
VALUES
  (1, 'admin.local', 'Administrador Local', 'Desarrollo local', 'LOCAL', TRUE),
  (2, 'sin.permisos', 'Usuario Sin Permisos', 'Mesa de ayuda', 'AD', FALSE);

INSERT INTO roles (id, codigo, nombre, descripcion, activo)
VALUES (1, 'ADMINISTRADOR', 'Administrador', 'Acceso total a los modulos del sistema.', TRUE);

INSERT INTO modulos (id, codigo, nombre, descripcion, orden, activo)
VALUES
  (1, 'EQUIPOS', 'Equipos', 'Inventario tecnico de computadoras y dispositivos principales.', 10, TRUE),
  (2, 'USUARIOS', 'Usuarios', 'Administracion de usuarios, roles, permisos y modulos.', 70, TRUE);

INSERT INTO permisos (id, codigo, nombre, descripcion)
VALUES
  (1, 'VER', 'Ver', 'Permite consultar informacion del modulo.'),
  (2, 'ADMINISTRAR', 'Administrar', 'Permite administrar configuracion del modulo.'),
  (3, 'EDITAR', 'Editar', 'Permite modificar registros existentes.');

INSERT INTO usuario_roles (usuario_id, rol_id)
VALUES (1, 1);

INSERT INTO rol_modulo_permisos (rol_id, modulo_id, permiso_id)
VALUES
  (1, 1, 1),
  (1, 1, 2),
  (1, 1, 3),
  (1, 2, 1),
  (1, 2, 2);

INSERT INTO equipos (
  id, nombre, ultimo_usuario, fuero, ip, sistema_operativo, procesador, ram_mb,
  ram_detalles, ram_seriales, discos_modelos, discos_seriales, motherboard_modelo,
  motherboard_serial, monitores, teclado, mouse, impresora, monitoreo, activo)
VALUES
  (1, 'PC-INF-001', 'gmurad', 'Informatica', '10.15.2.10', 'Windows 11 Pro', 'Intel Core i5', 16384,
   '2x8GB DDR4', 'RAMSN-001 | RAMSN-002', 'KINGSTON SA400', 'DISK-001', 'Dell 0ABC',
   'MB-001', 'Dell 22 SN MON-001', 'Logitech Keyboard', 'Logitech Mouse', 'HP LaserJet', 'REPORTADO', TRUE),
  (2, 'PC-MESA-002', 'mesa.entrada', 'Mesa de ayuda', '10.15.2.11', 'Windows 10 Pro', 'Intel Core i3', 8192,
   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'REPORTADO', TRUE);
