CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(120) NOT NULL UNIQUE,
  nombre_visible VARCHAR(180) NOT NULL,
  fuero VARCHAR(120) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE modulos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  orden INT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE permisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NOT NULL
);

CREATE TABLE usuario_roles (
  usuario_id BIGINT NOT NULL,
  rol_id BIGINT NOT NULL,
  PRIMARY KEY (usuario_id, rol_id)
);

CREATE TABLE rol_modulo_permisos (
  rol_id BIGINT NOT NULL,
  modulo_id BIGINT NOT NULL,
  permiso_id BIGINT NOT NULL,
  PRIMARY KEY (rol_id, modulo_id, permiso_id)
);

INSERT INTO usuarios (id, username, nombre_visible, fuero, activo)
VALUES
  (1, 'admin.local', 'Administrador Local', 'Desarrollo local', TRUE),
  (2, 'sin.permisos', 'Usuario Sin Permisos', 'Mesa de ayuda', FALSE);

INSERT INTO roles (id, codigo, nombre, descripcion, activo)
VALUES (1, 'ADMINISTRADOR', 'Administrador', 'Acceso total a los modulos del sistema.', TRUE);

INSERT INTO modulos (id, codigo, nombre, descripcion, orden, activo)
VALUES
  (1, 'EQUIPOS', 'Equipos', 'Inventario tecnico de computadoras y dispositivos principales.', 10, TRUE),
  (2, 'USUARIOS', 'Usuarios', 'Administracion de usuarios, roles, permisos y modulos.', 70, TRUE);

INSERT INTO permisos (id, codigo, nombre, descripcion)
VALUES
  (1, 'VER', 'Ver', 'Permite consultar informacion del modulo.'),
  (2, 'ADMINISTRAR', 'Administrar', 'Permite administrar configuracion del modulo.');

INSERT INTO usuario_roles (usuario_id, rol_id)
VALUES (1, 1);

INSERT INTO rol_modulo_permisos (rol_id, modulo_id, permiso_id)
VALUES
  (1, 1, 1),
  (1, 1, 2),
  (1, 2, 1),
  (1, 2, 2);
